- name: Install AD Domain Services
  win_feature:
    name: AD-Domain-Services
    include_management_tools: true
    state: present

- name: Promote server to a domain controller
  win_domain:
    dns_domain_name: "{{domain_name}}"
    safe_mode_password: M*S4B994spV14jcp/w
    #domain_mode: Win2012R2
    #forest_mode: Win2012R2
  register: dc_promotion

- name: Reboot server after promotion
  win_reboot:
  when: dc_promotion is changed